import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Autogenerated sidebars configuration for AI-Native Robotics
 *
 * This configuration automatically generates the sidebar structure based on:
 * - Folder hierarchy in the docs/ directory
 * - _category_.json files for customizing labels, positions, and collapsed state
 * - Alphabetical file/folder names (can be overridden with numeric prefixes or _category_.json)
 *
 * To customize a folder's appearance in the sidebar, add a _category_.json file:
 * {
 *   "label": "Display Name",
 *   "position": 1,
 *   "collapsed": false,
 *   "link": {
 *     "type": "generated-index",
 *     "description": "Chapter description"
 *   }
 * }
 *
 * Benefits of autogenerated sidebars:
 * - No need to manually update sidebar configuration when adding/removing files
 * - Folder structure directly reflects navigation structure
 * - Consistent ordering using _category_.json position values
 * - Less maintenance overhead
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;